### PR TITLE
Disable compile time optimisation -O2

### PR DESCRIPTION
**Pull request by okertanov**
via Martin Spasov: -O2 Causes just noise, when playing on my debian box. Compiled with gcc (Debian 4.4.5-8) 4.4.5
https://github.com/mspasov/shairport/commit/a4e0a53d9d7f996dc26d37371c36537cfd54916c

### CODE REVIEW

**Comment by albertz** [comment]
For you, too? See my comment on the commit. This is not the right fix. It is pure random that this change makes the noise go away. We should try to figure out why this happens. Unfortunately, I cannot reproduce the problem here.

**Comment by albertz** [comment]
Btw., why have you made this a manual commit and not just merged Martin Spasovs commit? That way, we have several unrelated branches now.

**Comment by Crazor** [comment]
Same problem here. -O2 gives stuttering on debian, while -O0 works.

**Comment by okertanov** [comment]
yes, reproduced with ubuntu 10.04 & iTunes 10xx. i'll try to debug the issue.
ok, reject this pool request and merge via Martin's one to be synchronized well.

**Pull request closed without merging**
