### PR TITLE
Added Squeezebox support

### PR DESCRIPTION
**Pull request by srcshelton**
This change adds additional command-line options (including one to write a PID file to a given location), and provides the facility to specify the cliport of a Squeezebox Server.

If enabled and able to be accessed, a per-connection routine will fire to automatically switch the Squeezebox (which must also be specified, if more than one is present) to play the AirPlay data.

I've tested the changes this evening and all looks good (although I can't figure out why attempting to send a 'power on' command to the player's server hangs the socket, whilst doing the exact same command via telnet has no problems).  More extensive testing would probably be helpful - and I'm more than happy for anyone to weigh-in and correct my somewhat rusty Perl ;)

(P.S. Is this sufficient to get me added to the list of contributors? ;)

### CODE REVIEW

**Comment by albertz** [comment]
First of all, thanks!

Several things about your commit:
- Avoid the `#!/bin/sh` hack.
- Avoid the reformating.
- You made _a lot_ of changes. I don't really see the reason for most of them. Can you split all changes up into several commits and comment on each one? And make separate pull requests if possible.

**Comment by srcshelton** [comment]
Commit ead60d4:
Perhaps some Perl ninja could suggest otherwise, but the existing fork()/daemonise code seemed to get things backwards.  Given my understanding of what this process should entail and the Perl documentation, I'd suggest the version included in this commit is more correct.  I'm happy to be corrected by more informed Perl hackers ;)

(Incidentally, this is also the sequence that Perl's Proc::Daemon module uses - and perhaps the best solution of all would be to use Proc::Daemon::daemon_init() instead of daemonising manually?  Other enhancements could be to add a post-fork 'close $_ for @_;' to close any open file-handles, and a second fork after calling sedsid() to guarantee complete detachment)

**Comment by srcshelton** [comment]
Commit e2da69d:
This brings us back up to the same state of the previous patch.  The code assumes that the Squeezebox Server is on the same host as ShairPort (which is probably a fair bet when we're using Named Pipes, not so much if AO is used...) and doesn't attempt to handle Squeezebox Server's (optional) security/authentication.  I have the CLI port of SBS listening on 127.0.0.1 in any case - and this is probably the advisable setup.

The one thing I've not been able to diagnose is why sending "<mac> power 1" is fine via telnet, but hangs shairport.pl the next time the socket is read from.  All other commands work.

I hope that these two commits make my changes sufficiently understandable to be accepted onto the master branch?  If there's anything that still needs work, please let me know!

All the best,

Stuart

**Comment by albertz** [comment]
Can you rebase it to clean it up and avoid those reformating commits?

**Comment by srcshelton** [comment]
Could you give me a clue about using the 'rebase' option (unless github allows this in a friendlier fashion)?
I'm still sorta stumped after reading git's documentation and searching Google (in that I understand the concept, but can't work out how to get git to rebase anything but the most recent change, d99abfc)

**Comment by albertz** [comment]
I mean `git rebase`. Probably the easiest thing would be to do `git rebase -i` and then get rid of the commits which shouldn't be there (i.e. all that do some reformating or so) and you can also merge commits together there, etc. And then, to push that, you need to do a `git push --force` because you have altered the history.

You have to specify the range for `git rebase`. I.e., start with the top of my master up to your head.

**Comment by askedrelic** [comment]
Might I suggest this practical guide for rebasing: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

More in depth, you have made 5 commits on your fork. You probably want `git rebase -i HEAD~5` and then you can squash all 5 of your commits into 1 single commit, which is easier to merge and view in the overall repo timeline.

**Comment by srcshelton** [comment]
Ugh - that was painful :(

Anyway - the above should be the changes in the form of two commits only (the first for debug/verbose messages & misc. fixes/cleanups; the second actually adding the Squeezebox integration code), for which all of the above comments should still apply.  Enjoy ;)

**Comment by albertz** [comment]
Thanks, that was in good shape now. :)

**Pull request merged**
