### PR TITLE
Optional alsa implementation for hairport

### PR DESCRIPTION
**Pull request by skaman**
Hi to all,
i'm proposing this fix for compile (optionally) shairport with alsa instead of ao
I'm working on an airplay server over a stb and i use hairport for itunes protocol but unluckily my system doesn't provide libao. So i made this patch for compile it with alsa instead of ao. I think this could be of interest for anyone want compile it on an embedded device.

Thanks :)

Sandro

### CODE REVIEW

**Comment by skaman** [comment]
This is not exactly what you asked for. But it clean the code inside hairtunes (i suppose this was your concern) and i thought it's really easy to understand from anyone need to add another audio implementation (maybe another os?)
What you think?

**Comment by skaman** [comment]
Sorry.. i missed a piece of code :)
Now it work :)

I've a question, the function hairtunes_init need also these arguments:
char*pPipeName, char *pLibaoDriver, char *pLibaoDeviceName

Hairtunes as standalone application set them directly inside the main, instead shairport do something strange:
first set 3 vars as NULL

```
  char *tAoDriver = NULL;
  char *tAoDeviceName = NULL;
  char *tAoDeviceId = NULL;
```

after it pass these vars without any modification to them

hairtunes_init(tKeys->aeskey, tKeys->aesiv, tKeys->fmt, tControlport, tTimingport,
                      tDataport, tRtp, tPipe, tAoDriver, tAoDeviceName, tAoDeviceId,
                      bufferStartFill);

Maybe there is something broken in shairport?

**Comment by sodabrew** [comment]
@skaman Just compiled this on my Chumby - it works great! Significantly more reliable than my libao build. I did have to use a large buffer (-b 128 results in many underruns, -b 512 works nicely).

@albertz Combined with the already-accepted mDNS support, these changesets allow Shairport to run directly on embedded Linux devices, Chumby in particular. I think the key problem might be needing Makefile options or (gasp) a configure script to detect/select compile settings...

**Comment by skaman** [comment]
If someone is interested:
- here there is a python implementation of shairport protocol (+ airplay protocol): https://github.com/E2OpenPlugins/e2openplugin-OpenAirPlay/blob/master/plugin/airplayserver.py
- here an example of bitbake recipe for compile hairtunes with openembedded: https://github.com/SIFTeam/openembedded/blob/master/recipes/sifteam/hairtunes.bb
- here the application in action: http://www.youtube.com/watch?v=RG7QnS7xCcw

**Comment by sjtoik** [comment]
Tested and works great.

**Comment by roji** [comment]
Same here, works perfectly and also seems more reliable than the libao build (will post if changes)

**Comment by therealmuffin** [comment]
Compiled the package with alsa and it works great. However, it does consume 50% percent more cpu than using it with libao. Does anyone else experience this? I'm using plughw with both options (changed that in audio_alsa.c).

**Comment by mikejuni** [comment]
I also have this compiled and working in OpenWRy after reverting some recent patch (which I will post later) only that CPU load is higher then the build from @albertz (I've pulled directly from @skaman ). But stability is good and I don't have skips whatsoever. Will try different compile flags to see I it improve the CPU load.

**Comment by therealmuffin** [comment]
@mikejuni : it seems we've been working partially on the same thing. I've directed the volume info to alsa mixer device and left libao with the internal mixer as it was. Pretty much as you're doing, but in a slightly different way. In addition made some configuration options. This seemed like the right moment to learn myself how to work github. I've created a fork. See if there is anything useful in there.

**Comment by mikejuni** [comment]
@therealmuffin looks like you have abstracted and refactored the code for mixer as well. I tried not to do it because I am more interested in pure C version of the shairport and don't want to make things too complex by changing the codes for hairtunes_init. Also the main objective of my code is to try to improve CPU utilisation by not having too much calculations (thus trying in compile time ignore volume soft setting and dithering) in order to make it work better in embedded environment (like OpenWRT and routers). Now with proper setting I could get CPU load down to 10% compared with 40% previously in my router (buffalo ag300h). Lets see if I could make use of some of your codes.

**Comment by albertz** [comment]
I'm not sure if this is really needed. libao is really lightweight. There shouldn't be any reason to not just use libao. If there are, libao should be fixed then.

**Comment by therealmuffin** [comment]
For just audio it works fine. However, since Airplay sends out mixer data we might as well use it. So my fork uses that data and sends it to Alsa. Works quite well I think.

**Comment by albertz** [comment]
What mixer data? What commit is that?

Btw., the commits also need some cleanup.

**Comment by therealmuffin** [comment]
I haven't submitted any commit's yet. I'm not much of a programmer and since Mikejuni is working on the same thing I figured I might better let him do it.

**Comment by albertz** [comment]
(For reference: [Here](https://github.com/mikejuni/shairport) is @mikejuni 's fork.)

About the mixer: Is it just the volume? That is a trivial calculation which can easily be done by hairtunes itself.

If so, I still don't really see the benefits. I only see that the code gets much more complicated.

**Comment by therealmuffin** [comment]
My soundcard supports mixer data. I prefer a hardware volume control over a software one, sounds a lot better. In addition I can control my amplifier with that data (volume wise).

**Comment by albertz** [comment]
I see. I just gave @mikejuni full access to this repo. He can merge his changes in once he feels that they are stable.

**Comment by therealmuffin** [comment]
Excellent, thanks.

**Comment by abrasive** [comment]
There is a major rewrite of Shairport in the works which includes modular audio - for details, see issue #188. The existing codebase will be no longer supported. Please consider porting your patch.

**Pull request closed without merging**
