### PR TITLE
Reorganize mDNS advertisement and add a few backends.

### PR DESCRIPTION
**Pull request by plietar**
This PR reorganizes the mDNS management in shairport.

mDNS is now handled more or less in the same way audio is.
Multiple mDNS backends are available, shairport tries them all until one
works.

This makes it, IMHO, cleaner, and easier to add other mDNS backends in
the future, such as using tinysvcmdns or dns-sd library.
Also it will also allow to define mDNS backends as plugins, in a similar
way it is done in PR #230.

The PR also adds two new mDNS backends : 
- `dns-sd` : uses mDNSResponder to advertise the service. However, instead of calling an external program, it uses the library provide by the `dns_sd.h` header available on OS X
- `tinysvcmdns`: embeds tinysvcmdns to advertise the service. Does not require an external daemon. However it is less robust and ~~does not support ipv6~~ I have now added ipv6 support. It may be a bit buggy.
  
  ~~It may be used while a mDNS daemon is running on the computer.~~ Seems to work in most cases, quite experimental tough.

### CODE REVIEW

**Comment by abrasive** [comment]
Hi Paul! Sorry for the delay in getting to this one. This is a great piece of work, and I'm sure a lot of people will be very grateful for the tinysvcmdns inclusion.

It doesn't compile for me - for one, dns_sd.h is present in some versions of Avahi. Perhaps a test that uses the compiler? Or perhaps a detected avahi install should disable mDNSResponder checking entirely -- as far as I know there's no system that would genuinely have both.

**Comment by plietar** [comment]
Thanks for the feedback.
What compile error do you get ? On my linux box (a raspbian) I don't have the `dns_sd.h` file.
Any way It's (I believe) a compatibilty layer to use software designed for bonjour on avahi. Build should be ok.
I'll have to improve to test in the Makefile.

I think the in house configure script is starting to show it's limits.
Whould you be against using some other tool, such as autotools ?

**Comment by abrasive** [comment]
The link step fails - none of the Bonjour symbols are available. They don't need some linker flags on OS X? I think it would be appropriate to test for bonjour only if avahi is not found.

autotools is definitely not OK, and I'd be pretty leery of cmake too.

**Comment by abrasive** [comment]
Finally merged! Thanks again for the contribution, this is really useful.

**Pull request closed without merging**
