### PR TITLE
shairport.pl minor changes...

### PR DESCRIPTION
**Pull request by srcshelton**
This change allows perl to be invoked as 'perl -w' and adds 'use strict;'.  It then fixes the issues that this highlights ;)

Note that I've commented out the code which tries to build hairtunes and fails instead.  Feel free to reject this part, but I wasn't comfortable with the idea of automagically running make without checks for what directory shairport.pl was invoked from or that we've even got the right Makefile and that the code hasn't been altered.

I can understand trying to be friendly out-of-the-box, but is it too much to ask that people read INSTALL?  If they're not going to do this, there's little help...

In any case, hope this helps,

Stuart

### CODE REVIEW

**Comment by albertz** [comment]
I merged it in. Though, I removed the shell-wrap hack again in [this commit](https://github.com/albertz/shairport/commit/d972fcd8328c21a7579dff6e4a7e7ac42cf18ffb) because it caused warnings here and it should work anyway if you just use `perl -w shairport.pl` and probably many people don't want it this way. And after all, `shairport.pl` should print useful warnings anyway, also when not started with `-w`.

**Comment by srcshelton** [comment]
Fair enough.

Out of interest, though, what warnings did you see?  I'm on perl 5.12.2, and the code-changes in the push fixed all warnings I came across...

**Comment by albertz** [comment]
```az@Albert-Zeyer-MacBook-Pro 1161 (shairport) %./shairport.pl 
v-string in use/require non-portable at ./shairport.pl line 40.
Can't exec "avahi-publish-service": No such file or directory at ./shairport.pl line 153.
Registering Service 0051F2CD5C4F@ShairPort 10817 on Albert-Zeyer-MacBook-Pro.local._raop._tcp port 5000 TXT tp=UDP sm=false sv=false ek=1 et=0,1 cn=0,1 ch=2 ss=16 sr=44100 pw=false vn=3 txtvers=1
listening...
11:53:40.838  Got a reply for service 0051F2CD5C4F@ShairPort 10817 on Albert-Zeyer-MacBook-Pro.local._raop._tcp.local.: Name now registered and active
^Ckilled

``````

Also, this didn't worked at all:
```az@Albert-Zeyer-MacBook-Pro 1157 (shairport) %perl -w shairport.pl 
/bin/sh: -w: invalid option
Usage:  /bin/sh [GNU long option] [option] ...
...
``````

Also, I saw you added a check for Perl 5.10.0. Isn't that what `use 5.10.0;` does already?

**Comment by srcshelton** [comment]
I didn't see the Line 40 warning, but I guess that's from 'use <version>'... see here for a further discussion:

http://www.effectiveperlprogramming.com/blog/396

The logic at the top doesn't handle parameters, it's intended for when the script is invoked directly (which I'd suggest is going to be the majority of the time).  From perlrun(1), a suggested header is:

```
       #!/bin/sh
       #! -*-perl-*-
       eval 'exec perl -x -wS $0 ${1+"$@"}'
           if 0;
```

The 'use <version>' syntax, as mentioned, only works for versions of perl more recent than a certain point - perl 5.8, IIRC.  For older versions, the 'use' line will generate a warning but execution will attempt to continue regardless.  The logic at the top merely gives these potential users a clean error message rather than a stack of compilation failures.

**Comment by albertz** [comment]
I just checked it. http://perldoc.perl.org/functions/use.html
It doesn't work prior to 5.6.0. That was released in March 2000. So more than 10 years ago. We shouldn't take any care about that. Nobody should use such old stuff anyway and he might have other problems than to use ShairPort.

`use 5.10.0;` is just much more clean and clear than the hack. So I guess we should leave it like this.

**Pull request merged**
