### PR TITLE
fix retransmit: make sure to report our control port at setup

### PR DESCRIPTION
**Pull request by Nachtzuster**
For some reason, the code expects retransmit data to be also sent to the audio port.
This tells the connecting play to do so.
verified to work with Airfoil 3.5.3, Eric Milles' Remote Speakers Output Plug 4.7 and iTunes 10.5.3.3

Frederik

### CODE REVIEW

**Comment by Nachtzuster** [comment]
'we' used to just take the setup string from the client and stick our ';server_port=xxx' on.
in other words, we were telling the client our control and timing port was the same as theirs.
Now we are giving the control_port we are actually listening on.
Timing port is still theirs, though, but it is not used anyway.

**Comment by abrasive** [comment]
I was actually wondering about the "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record".

I forgot to credit you in the commit, sorry; have fixed it up. I also went with using the same local port for all three, for now; if it turns out to be a performance issue then we can split them later.

**Comment by abrasive** [comment]
Oh, I'm an idiot. Ugh. Will fix my "fix", as what I committed will tag extra ports _on the end_.

**Comment by Nachtzuster** [comment]
I had a look at you variant, this was actually very close to my first, failed, attempt :-)

**Pull request closed without merging**
