### PR TITLE
using gcc as the default compiler

### PR DESCRIPTION
**Pull request by rene-dev**

### CODE REVIEW

**Comment by albertz** [comment]
Why? Maybe people want to use different compilers.

**Comment by rene-dev** [comment]
ok, just a thought to use gcc as the default...

**Comment by albertz** [comment]
The system should define the default compiler. Our makefile should not overwrite this.

**Comment by rene-dev** [comment]
I see, for some reason the toolchain for the motorola vip1710 does not provide a symlink.

**Pull request closed without merging**
