### PR TITLE
Add metadata support

### PR DESCRIPTION
**Pull request by wnielson**
This adds the ability to save metadata about the currently playing track, including artist, track, album and artwork.  Much of the work was done by [allesblinkt](https://github.com/allesblinkt/shairport), I just cherry picked his changes, merged them with the current branch and made a few improvements.

### CODE REVIEW

**Comment by peec** [comment]
+1 for this awesome feature. Great for integration with other apps. Even though JSON might be a better format for the file itself instead of newline separated.

**Comment by fatso83** [comment]
:+1:

**Comment by abrasive** [comment]
Merged as `metadata` branch with FIFO support. @allesblinkt, I have credited you as 'allesblinkt' with a link to your GH page in the `README.md`, what would you prefer? @wnielson, and you?

Test reports welcome, will promote to master in a few days if I don't hear anything terrible.

**Comment by allesblinkt** [comment]
@abrasive Oh, I overlooked this. Crediting as allesblinkt with the link to GH is fine. 
Thank you very much!

**Comment by abrasive** [comment]
Merged. Thanks, everyone!

**Comment by mcantarutti** [comment]
Hello, I'm having trouble with line   

rtsp.c:469 uint32_t vl = ntohl(*(uint32_t *)(cp+off));

which then occasionates a segfault with 
char *val = malloc(vl+1);

after a couple of loops.

I am running the code in a arm with arch.

removing the ntohl() seems to help but I've no idea which is the background problem...

Hope this helps.

Thanks!

**Pull request closed without merging**
