### PR TITLE
Gentoo init script

### PR DESCRIPTION
**Pull request by firelizzard18**
This is a relatively trivial change that adds a init.d script and a conf.d file for gentoo. In the Makefile, I renamed `install` to `install-exe`, added a new `install` that just depends on `install-exe` and `install-init`, and added `install-init` that detects Gentoo and installs the scripts to their respective locations.

The init script checks for various variables and adds any corresponding options.

### CODE REVIEW

**Comment by jclehner** [comment]
Wouldn't it be better to write an `.ebuild` instead and install the initscript from there? Also, checking `/proc/version` just tells you that the kernel was _compiled_ on Gentoo, not that it's actually running Gentoo!

**Comment by firelizzard18** [comment]
I'm not familiar enough with `.ebuild`s to make one. That initscript is (basically) the one I made for and I'm currently using with my system.

Do you happen to know of a better way of checking the current running version?

**Comment by jclehner** [comment]
On both of my Gentoo systems there's a file called `/etc/gentoo-release` which is owned by the `baselayout` package; I'd say that's your best bet!

I might hack together an `.ebuild` if I find the time to do so!

**Comment by abrasive** [comment]
Thanks for the patch! I'd love to have the Gentoo needful in the tree. There are a few little things that need to be addressed before I can merge this.
- Changes to the Makefile will not be accepted. Please make an ebuild, that'd be perfect.
- What is the copyright notice doing in init.d.sh?
- You almost certainly want a -- before $BACKEND_OPTS on init.d.sh line 37
- the long options like error and output should be set with double dashes --output= etc.
- if someone hasn't explicitly specified a logfile, then don't log; if logging is wise by default then enable it in the cfg file (ref init.d.sh line 32-33).
- a comment in the cfg file on how to ask shairport for the available backends & their options would enlighten new users.

**Comment by abrasive** [comment]
Sorry this got dropped. I'll consider an ebuild & associated files if someone can pop up an up-to-date verson.

**Pull request closed without merging**
