### PR TITLE
implement start/stop command

### PR DESCRIPTION
**Pull request by MaZderMind**
Hi

I use this to turn on/off my stereo via gpio using the perl script. implementing this in your 1.0-dev codebase is quite simple, as long as you regard player.c to be the correct place to call those commands.

Regards

### CODE REVIEW

**Comment by MaZderMind** [comment]
Hmm well I should have testet that in the wild before; fails with

```
Shutting down...
Got SIGTERM, quitting.
failed to accept connection: Interrupted system call
failed to accept connection: Interrupted system call
```

on my raspi, have to check why

**Comment by abrasive** [comment]
Did you get this one working?

**Comment by MaZderMind** [comment]
No but I know what the problem is: launching the subprocess from the player thread makes it receive signals from that subprocess. One of these signales interrupt a connect()-call somewhere else in the code.

I see that I'm novice when it comes to unix multithreading, so I'll have to try different solutions:
- block signales from the thread: http://stackoverflow.com/a/8093964/1659732
- use SA_RESTART http://permalink.gmane.org/gmane.comp.standards.posix.austin.general/6362
- handle EINTER on the connect() http://www.madore.org/~david/computers/connect-intr.html

**Comment by abrasive** [comment]
You need to be careful here - signals are essential to the RTSP multiple connection handling functionality. Also if your external script takes too long at startup, the connection might run into trouble.

fork() would be a better choice from an isolation point of view, but then you start getting SIGCHLD instead - which is currently used to detect death of the mDNS advertising subprocess.

Any idea if SIGCHLD is delivered to the parent thread of the subprocess, or to any old thread that has SIGCHLD unblocked?

**Comment by abrasive** [comment]
You could block SIGCHLD globally (in the main() before threads are spawned) and then add a thread in the mDNS handler that does nothing but waitpid()... but there'd need to be a wait somewhere else to mop up all the dead subprocesses too.

**Comment by abrasive** [comment]
I'd like to have this functionality in the 1.0 release. We need to figure out how to do this right.

**Comment by chappy72** [comment]
I am interested in using a gpio to switch inputs on my radio already got the circuitry figured out and working but, I am super new to all things unix so i dont think i will be of much help as far as the coding goes, but i figured i would say something ...

**Comment by abrasive** [comment]
Implemented. Thanks for the patch!

**Pull request closed without merging**
