### PR TITLE
proposed patch for bug #303

### PR DESCRIPTION
**Pull request by gonewest818**
Proposing a fix for bug #303, where libao audio goes silent on raspberry pi after a day (or maybe longer) of idle time.   This patch is admittedly incomplete, but I wanted your feedback on the approach before going any farther on it.  

The idea is to close audio when shairport goes idle, and open audio when there is new music to play.  To accomplish this I
- added a command line flag
- added a int (*reinit)(void) to the audio_output struct
- in audio_ao **only** (for now) I implemented the reinit() function
- in rtsp.c, added the logic to shutdown/restart audio after idle periods

I've been testing this as home for two weeks and it has resolved the bug for me.  If you are ok with this direction then what remains is implementing similar init/deinit/reinit logic for the other audio drivers.

### CODE REVIEW

**Comment by abrasive** [comment]
#297 does this too, without changing the individual drivers. I'm not sure about this; it introduces the possibility of runtime crashes of audio drivers if the audio situation changes. Perhaps they need to be reworked to report errors and ditch the connection rather than dying.
Also, @ejurgensen, will forked-daapd be happy with a closed pipe?

**Comment by gonewest818** [comment]
I saw #297 and your objection to it ... the (sort of) difference here is that the full audio stack does initialize immediately and you would get prompt feedback of a failure.  It does not solve the case where the audio situation changes, but then again -- I'm experiencing the problem right now where the audio situation has changed and all I get is silence.

So for instance let's say I do catch the return code from ao_play() and detect an error...  I could try to re initialize audio based on that error, but what if that fails? Is that any better than failing this automatic deinit/reinit ?

Just my opinion, totally up to you.

**Comment by gonewest818** [comment]
Also fwiw this patch has been running on a rpi continuously for 6 weeks, never rebooted not even the process restarted as far as I can recall.  In my case anyway this has solved the problem completely (although to be fair I still lack any true insight what the underlying issue is/was).

**Comment by ejurgensen** [comment]
No-one likes a closed pipe ;-) But forked-daapd can kinda handle it, since it opens the reading end with nonblock. I didn't test this change, but I have tested that it is possible to start Shairport, begin streaming through a pipe to forked-daapd, shutdown Shairport, restart it and continue streaming. However, as I recall, forked-daapd does not detect the pipe closing, so it doesn't close/reopen the streams to its own AirPlay targets - which is not so nice. I should fix that at some point.

**Comment by gonewest818** [comment]
I finally confirmed that a recent clone of this project using alsa rather than libao does not exhibit the big reported in #303. I'm closing this pull request as no longer relevant.

**Pull request closed without merging**
