### PR TITLE
Improve daemon mode

### PR DESCRIPTION
**Pull request by plietar**
The daemon's process id can be written to a file, and output can be redirected to a logfile.
This makes it easier to write complete init-script.

### CODE REVIEW

**Comment by abrasive** [comment]
Thanks for the patch! This code looks very good, and I think splitting out the daemonising code is an excellent idea.

Just a couple of issues to clean up:
- getopt_long is a GNU extension. Everything previously is strictly POSIX (or at least I've tried to make it so). Can this cleanly be made optional, do you think?
- Please use the same brace style as elsewhere.

**Comment by abrasive** [comment]
Your Pulseaudio patch highlights that init()ing audio before forking is a bit silly.

Might this be a good point to move the fork much earlier? We could use a pipe to notify the spawning process whether the init steps succeeded or not, at which point it can exit.

**Comment by plietar** [comment]
About getopt_long, I believe the options are clearer using long names, and avoid mixing up.
Why not include an implementation of getopt_long on non-GNU platforms ?
There's one there : http://www.netmite.com/android/mydroid/external/androidmono/mono/msvc/getopt_long.c

**Comment by abrasive** [comment]
I agree that long options are desirable. It needs to not be in the log redirection patch, though :) I'll include the Postgres getopt_long implementation now.

**Comment by abrasive** [comment]
The fork() has also been moved up. Sorry for breaking your patch.

**Comment by plietar** [comment]
I've rebased the commits on 1.0-dev
The daemon related code is in a different file, including the pipe communication.
For now the log redirection is left in shairport.c, as I think it can be useful in non-daemon mode too.

**Comment by abrasive** [comment]
Merged. Thanks, Paul!

**Pull request closed without merging**
