### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by pepijndevos**
Changed the Makefile as discussed in #8 and added instructions to the installation file.

### CODE REVIEW

**Comment by pepijndevos** [comment]
Do they still exist? Will this work on PPC as well then? Is it relevant to this pull? :)

If it even works on Windows, I'm sure Macports can compile all the perquisites on PPC and 32 bit as well. At least someone must be running Leopard...

**Comment by mspasov** [comment]
I don't have access to PPC based Mac.. Let's keep the docs pointing to
<pre>ARCHFLAGS="-arch x86_64"</pre>, and if there's a problem, someone will report it.

ps, It took me some time to figure this out, before this was available in INSTALL file.

**Comment by pepijndevos** [comment]
Oh that is what you are referring to. Well, I suppose you should just set it to whatever arch you have.

On second thought, running `arch` returns i386 even on my machine, so I guess that's why. Can anyone confirm `echo $HOSTTYPE` returns the right thing everywhere?

Maybe this should be in the makefile rather than in an extra command.

**Comment by mspasov** [comment]
Can't be in our Makefile :). This is only needed for the perl modules compilation.

**Comment by albertz** [comment]
`$HOSTTYPE` is unset on my machine.

**Comment by mspasov** [comment]
`$HOSTTYPE` is set by bash, and we cannot expect all users to use bash on macos. Not a reliable source:

<pre>
Avatars-MBP:~ avatar$ set |grep HOSTTYPE
HOSTTYPE=x86_64
Avatars-MBP:~ avatar$ sh
sh-3.2$ set |grep HOSTTYPE
HOSTTYPE=x86_64
sh-3.2$ csh
[Avatars-MBP:~] avatar% set |grep HOSTTYPE
[Avatars-MBP:~] avatar% sh
sh-3.2$ set |grep HOSTTYPE
HOSTTYPE=intel-mac
</pre>


I think we should stat that only for Xcode4 user should set `$ARCHFLAGS` to `-arch i386 -arch x86_64` (because Xcode4 lost support for ppc and ppc64) and for Xcode3 the default will work (cross compile for all architectures).

**Comment by albertz** [comment]
I would prefer to not clutter the doc with information which is only for very specific cases for people who should know anyway what they are doing. People only need cross compiling for PPC if they really want to redistribute it. And as said, I think PPC (i.e. big endian) is probably broken anyway. But I didn't tested it. I'm not sure if anyone did.

**Pull request merged**
