### PR TITLE
C Only implementation

### PR DESCRIPTION
**Pull request by Andywebs**
I've re-implemented the shairport.pl in c.  It doesn't have all of the functionality of the perl version, but it does have most.  Some people on the openwrt forums were requesting a non-perl version for space/memory reasons.

Missing:
  pipe support > raw file
  full ipv6 support.
  some of the new options added in the last few days.

### CODE REVIEW

**Comment by Stevo83** [comment]
Thanks a lot for putting this up. I will try to run this on my router in the next days.

**Comment by albertz** [comment]
Isn't the pipe support trivial in the sense that it only forwards the cmd-parameter to hairtunes? I haven't really looked at it...

I think the IPv6 support is quite important though. There were many discussions about it and I'm not sure if it may break things if IPv6 is not supported. Somebody should check this. Or just implement it.

Btw., you have put the private key into a separate file and commented it out from the source. Why?

**Comment by Andywebs** [comment]
All of your points are valid, if someone else doesn't get to them first, I'll definitely fix it.  I've been avoiding working on a take home final for my class, and really need to get to it.  I had noticed the flurry of development on the perl version, and thought I should get in what I had worked on.

The IPv6 Support is ALMOST there.  The only thing I didn't finish was conversion of the ipv6 format from colon notation to the joined binary.  All of the socket communications are ipv6/ipv4 agnostic.  I couldn't figure out how to get the iphone to connect over ipv6, it didn't seem possible.

I wanted to compile the private key in, but couldn't figure out how to do it with the methods that openssl provides.  There may be some C trick that would do it, but my C is about 10 years from being an everyday language.

If these deficiencies aren't fixed by May 9th, i'll be back to working on them.

Andrew

**Comment by dapperfu** [comment]
Could you also add all of the functionality to specify the output sink?

**Pull request merged**
