### PR TITLE
Fixes ApName problems when compiling for OpenWRT

### PR DESCRIPTION
**Pull request by osheroff**
ApName was consistantly blank on openwrt w/out this fix.

### CODE REVIEW

**Comment by albertz** [comment]
Why should that commit change anything?

You replaced `char tServerName[56] = "ShairPort";` by `char tServerName[56]; strcpy(tServerName, "Shairport");`.

Also, why have you changed `"ShairPort"` to `"Shairport"`?

**Comment by osheroff** [comment]
Eh, you're right, that commit doesn't change a thing.  The ApName certainly _was_ turning out blank, but that wasn't the reason.  Nor do I have a repro now.   So, nevermind.

**Comment by xseregax** [comment]
May be change char tHWID_Hex[HWID_SIZE \* 2] to char tHWID_Hex[HWID_SIZE \* 2 + 1];

**Comment by albertz** [comment]
Yea you are right.

**Pull request closed without merging**
