### PR TITLE
Add in launchd script for OS X

### PR DESCRIPTION
**Pull request by casr**
Set up a daemon service for OS X using launchd that loads on boot.
The script depends on the computer having a network connection and
upon the mDNSResponder and coreaudiod running before it launches
shairport.

### CODE REVIEW

**Comment by abrasive** [comment]
Wonderful! A launchd plist has been in my TODO list for about a year. Unfortunately I don't have the machine to test one...
Can you fix the small typos (deamon->daemon) and check that it works with the latest master? Then I'll merge it.
Thanks very much!

**Comment by casr** [comment]
I've fixed that typo and rebased on master. I'll try and test properly tomorrow if I find the time!

**Comment by plietar** [comment]
@casr About using launchd to advertise the service, AFAIK launchd doesn't support TXT records, which is required by airplay.
See https://lists.macosforge.org/pipermail/launchd-dev/2010-August/000829.html

**Comment by abrasive** [comment]
Great! Thanks.

**Comment by casr** [comment]
@plietar ah I was unaware of that. I've had a quick look around the man pages and the Internet and the situation appears unchanged. Shame! I'll remove the note from the commit message.

**Comment by casr** [comment]
@abrasive I've tested now and should be ready to merge (ignoring the issues with #321)

**Comment by abrasive** [comment]
Merged! Thanks. Also fixed the #321 issue, thanks for pointing that out!

**Pull request closed without merging**
