### PR TITLE
Detect supported audio output drivers at runtime

### PR DESCRIPTION
**Pull request by plietar**
Currently, shairport is dynamically linked to multiple audio output libraries, such as libpulse, or libao.
Whether or not support for these libraries is built is determined at build time, depending on the presence or not of development packages of the library.

I think it would be better to have a binary that supports all existing drivers supported by the os (obviously not alsa on osx for example), and determine at run-time if the library is available.
This would allow to have a single binary, which could be distributed in a deb or an rpm file, but not require all the libraries on the computer on which it is installed.

Two methods come to my mind : 
- Build the output drivers in seperate '.so' files, and load them as plugins using dlopen and dlsym. This allows to add more drivers without rebuilding everything (not really important though, total build time is 10sec)
- Build the output drivers inside the shairport binary, and use the audio libraries with dlopen and dlsym, if they are installed. This makes drivers a bit more complex to write, but requires a single binary file.

I think the second solution is the best, I like the idea of a single file. 
What's your opinion ? I'm willing to do it.

### CODE REVIEW

**Comment by plietar** [comment]
The second method implies static linking is not possible. Is that a problem ?
The modularity could be disabled at build time, with a configure option, to make it possible to link statically.

**Comment by plietar** [comment]
I believe I'll go with the first option finally.
Locating the shared libraries for dlopen is way too difficult.
Output driver plugins make it possible to rely pkg-config and gcc to locate shared library.
Unless someone knows another way of doing it ?

**Comment by abrasive** [comment]
I think the first is the best approach.
Static build still needs to be an option for lower-end embedded devices.
The helptext for each driver might need to move to audio.c, so that it doesn't bomb when displaying usage. That'd make it easier to format consistently too.

My main concern is complexity. How are you intending to build libraries in a portable way? From memory, it takes a fair bit of GNU-specific incantation to get ld to spit one out on Linux.

**Comment by plietar** [comment]
Isn't `-fPIC` and `-shared` enough ? I'll work on it tomorrow.
I don't understand why you want to move drivers' help in audio.c ?

**Comment by abrasive** [comment]
Because the global usage function rolls through all the drivers' helps now, so if one driver doesn't load, its help won't be available. Could just display a message to that effect, I suppose.

**Comment by abrasive** [comment]
Compilers other than gcc will barf. Also, the rpath needs to be set according to the install dir, which isn't even vaguely portable. I'm not liking the added complexity for such a limited benefit.

**Comment by omor1** [comment]
When this graduates to 1.0 and is (possibly) put on distributions' repositories, it would be nice to have this feature.
Otherwise, the only way it could be installed is if it was compiled for all three backends and all of them were listed as dependencies, which is bothersome and clunky for the end-user.
Out of the two options, it seems that the first is the easier and better option.
Perhaps it is worthwhile to see how other software with multiple backends deal with this situation?

**Comment by plietar** [comment]
I've started working on it.
Not sure it is portable right now. On what compilers should it work other than gcc ?
@omor1 making it suitable for distributions is what I had in mind.

**Comment by abrasive** [comment]
OS X is actually the most common hairy case and should be easy enough to detect. Cygwin has some quirks too if I remember correctly. On reflection, as long as it fails gracefully, it really doesn't have to work everywhere. If you're using Cygwin you're already screwed.

Of course, libtool is an option, but... sledgehammer.

**Comment by plietar** [comment]
Almost there !
libtool is not used finally. This implies the use of a file per platform to define the correct flags.
I've wrote the files for linux and osx. Can someone try on other platforms (Cygwin/Mingw, BSD, ...).

`make install`is required so that shairport can find the modules. For now, prefix is defined by environment variable when running configure. Have to add a command line flag.
I might add a 'development' mode (chosen at build time), which would cause shairport to look in current directory rather than installation directory.

Also static plugins are not implemented (Yet !)

**Comment by sm3rt** [comment]
Hi I know it's probably a bit late but had you thought of using http://www.portaudio.com/ this would make cross platform and sound simple? It's used in squeezeslave https://code.google.com/p/squeezeslave/ which compiles and works well on openwrt and clearly other platforms. The sound quality is better than shairport currently as it suffers from no occasional noise.

**Comment by omor1** [comment]
Note that ./configure scripts generally take long-format options: --help and --prefix=PREFIX, for example.
Take a look at https://www.gnu.org/prep/standards/html_node/Configuration.html.
Of course, this is neither GNU software nor released under the GNU GPL, but nevertheless, it would be nice to implement this.

**Pull request closed without merging**
