### PR TITLE
Don't send silence if buffer is underrun in infinte loop

### PR DESCRIPTION
**Pull request by jishi**
I don't understand why it should send silence if the buffer is underrun. Not only does it garble the output, if you pipe to a file this file grows several into GB sizes in seconds? That can't be good.

It also lowers CPU usage in my tests. 

reproduce:
touch /tmp/output.bin
./shairport -o pipe /tmp/output.bin

Connect Airplay device, stream for a bit. Shut it down, and look at the size of /tmp/output.bin

### CODE REVIEW

**Comment by abrasive** [comment]
This output is called 'pipe', not 'file'. It's for streaming to realtime consumers.

Shairport manages the audio resampling rate to very delicately match the sender and the output device, so the buffer stays filled (but neither over- nor under-filled).
In order to do so it expects the consumer to buffer some frames at the start, then consume at real time, plus or minus a few percent.
And it sends silence when packets are missing to keep normal audio drivers happy.

If you pipe it to a file, you end up reading at hundreds of times realtime speed, which it will faithfully try and adapt to and fail.
If you want file output for whatever strange reason, make a file output out of audio_dummy.c, which has accurate sleeps between consuming frames for just this reason.

**Comment by jishi** [comment]
Hm, alright, I follow you. But the file was just an example, the real user scenario was actually a fifo pipe which was read and forwarded over http to a streaming client. The problem that occured was that it flooded the fifo with 0x00 and audio only came through every minute or less.

I realize that my user case is a bit edge, but the behavior still didn't seemed right. Of course, the other end of the pipe did try and read as soon as there was data there, but it just got filled with 0x00 then, of course. 

I have seen people piping the output to vlc and transcoding in realtime to MP3, are you saying that a software like that would only read at the same rate as the audio should arrive (taking sample rate and sample size in account)?

I guess the correct approach would be to block the fifo from the other end and just read samplerate  \* channels \* 2 bytes per second then. Sorry for the confusion.

**Comment by abrasive** [comment]
Yes, ideally you should do flow control yourself. You can also use the dummy output and tap the data on the way in to alac_decode() if you want an ALAC stream and the consumer is smart enough to do its own rate control for streaming sources.

**Comment by jishi** [comment]
Gotcha. When you say tap, you mean modifying the source, not that there is some sort of hook with the dummy output? Because I can't figure out how that would work in that case.

**Comment by abrasive** [comment]
Yes. You'll probably need to generate and output an alac header, the source sends the relevant parameters but not the header itself. You can reconstruct it using David Hammerton's original alac decoder source, which reads such a header into the relevant fields for the decoder.

Using the dummy output ensures sane timing.

**Pull request closed without merging**
