### PR TITLE
Previously the number of players would be detected as one regardless of number of players.

### PR DESCRIPTION
**Pull request by magnusmoaner**
Fixed a bug in the regular expressions used to fetch number of players, and changed the loop to fetch mac adresses for each player

### CODE REVIEW

**Comment by albertz** [comment]
It seems your formatting is wrong. Can you fix that?

**Comment by magnusmoaner** [comment]
There. That should do the trick

**Comment by albertz** [comment]
Can you rebase that? I.e. `git rebase -i` and squash/fixup them.

**Comment by magnusmoaner** [comment]
I'd love to, but I'm not that familiar with git so I couldn't get it work properly. A little help would be appreciated =)

**Comment by albertz** [comment]
Go into the directory, then type `git rebase -i <last-revision>`, then do a fixup (it is all explained there how to do that), then type `git push --force` and then update this pull request.

**Comment by magnusmoaner** [comment]
Thanks. And now it's updated.

**Pull request merged**
